export const BASS_TYPES = {
  sub: {
    label: 'Sub',
    desc: 'Sine puro muy profundo, sin armónicos. Ideal para sub-graves electrónicos.',
    oscType: 'sine',
    envelope: { attack: 0.005, decay: 0.5, sustain: 0.75, release: 0.4 },
    filterFreq: 220,
    vol: 0.95,
  },
  synth: {
    label: 'Synth',
    desc: 'Sierra analógica con body brillante y presencia. Bajo polivalente.',
    oscType: 'sawtooth',
    envelope: { attack: 0.003, decay: 0.25, sustain: 0.75, release: 0.2 },
    filterFreq: 800,
    vol: 0.90,
  },
  acid: {
    label: 'Acid',
    desc: 'Cuadrada con filtro resonante, el bajo acid house / techno clásico.',
    oscType: 'square',
    envelope: { attack: 0.001, decay: 0.20, sustain: 0.65, release: 0.15 },
    filterFreq: 500,
    vol: 0.88,
  },
  pluck: {
    label: 'Pluck',
    desc: 'Bajo pulsado tipo Karplus-Strong. Ataque percutivo, decay natural.',
    oscType: 'pluck',
    envelope: null,
    filterFreq: 1000,
    vol: 0.90,
  },
  k808: {
    label: '808',
    desc: 'Sub sine con sustain largo, el bajo 808 clásico del trap / R&B.',
    oscType: 'sine',
    envelope: { attack: 0.001, decay: 1.5, sustain: 0.75, release: 1.0 },
    filterFreq: 160,
    vol: 0.97,
  },
  reese: {
    label: 'Reese',
    desc: 'Dos sierras detuneadas agresivas, el bajo reese del DnB y dubstep.',
    oscType: 'fatsawtooth',
    envelope: { attack: 0.003, decay: 0.25, sustain: 0.92, release: 0.2 },
    filterFreq: 700,
    vol: 0.90,
  },
  fingered: {
    label: 'Fingered',
    desc: 'Triángulo con ataque rápido, simula el bajo eléctrico tocado con dedos.',
    oscType: 'triangle',
    envelope: { attack: 0.001, decay: 0.28, sustain: 0.40, release: 0.35 },
    filterFreq: 900,
    vol: 0.88,
  },
  wobble: {
    label: 'Wobble',
    desc: 'Sierra con LFO sobre el filtro, el wobble bass del dubstep sincronizado al BPM.',
    oscType: 'sawtooth',
    envelope: { attack: 0.003, decay: 0.35, sustain: 0.85, release: 0.2 },
    filterFreq: 350,
    vol: 0.90,
    wobble: true,
  },
};

export const bassOpts = Object.entries(BASS_TYPES).map(([v, o]) => ({
  v, label: o.label, desc: o.desc,
}));
